hostname dc1-dist
log stdout
!
interface eth1
 description Link to DC1-Edge
 ip address 10.1.0.2/30
 ip ospf network point-to-point
 ip ospf area 0
!
interface eth2
 description LAN to DC1-Srv
 ip address 10.1.10.1/24
 ip ospf area 0
!
router ospf
 ospf router-id 10.1.255.2
!
line vty
!
