hostname dc2-dist
log stdout
!
interface eth1
 description Link to DC2-Edge
 ip address 10.2.0.2/30
 ip ospf network point-to-point
 ip ospf area 0
!
interface eth2
 description LAN to DC2-Srv
 ip address 10.2.10.1/24
 ip ospf area 0
!
router ospf
 ospf router-id 10.2.255.2
!
line vty
!
