hostname dc2-edge
log stdout
!
interface eth1
 description Link to WAN-R1
 ip address 10.100.2.2/30
!
interface eth2
 description Link to DC2-Dist
 ip address 10.2.0.1/30
 ip ospf network point-to-point
 ip ospf area 0
!
router ospf
 ospf router-id 10.2.255.1
 redistribute bgp
!
router bgp 65200
 bgp router-id 10.2.255.1
 no bgp ebgp-requires-policy
 neighbor 10.100.2.1 remote-as 65000
 neighbor 10.100.2.1 description WAN-Core
 !
 address-family ipv4 unicast
  neighbor 10.100.2.1 activate
  redistribute ospf
 exit-address-family
!
line vty
!
